### ISSUE TITLE
What would solarized dark 1.0.0 look like?

### ISSUE THREAD

**Issue by schmittyjd** [atom/solarized-dark-syntax#52]
Just wondering, as we are now at version 0.40.0. What do you all think would constitute 1.0.0? I mean it is just syntax highlighting, so I don't think moving to 1.0.0 would be too much trouble. Thoughts? @atom/solarized-maintainers

**Comment by simurai** [comment]
I think it's a good idea to release the current version as `1.0.0`. It doesn't necessarily need new "features", but just to say that it's compatible with Atom 1.0.

**Comment by benogle** [comment]
Sure, just do it

**Comment by simurai** [comment]
Something that might be worth to sneak in before: Unifying solarized dark and light.

I have to look into it if it's possible, but the idea is like this: Both themes would be identical except maybe for the `variables.less` and `syntax-variables.less` files. The benefit would be that if somebody makes a PR to Solarized __dark__, let's say change something in the `python.less` file. Then we can just copy&paste that change over to Solarized __light__ as well. So that both versions would get updated.

@schmittyjd let me know if you think it's a good idea and I'll take a look.

**Comment by schmittyjd** [comment]
@simurai a unification of the repos could be nice.

**Comment by simurai** [comment]
ok, I'll give it a try.. and once it's done, we can release both as `1.0.0`.

**Comment by schmittyjd** [comment]
@benogle appropriate
![](http://media.giphy.com/media/Z0dvuZszc3r3i/giphy.gif)

**Comment by benogle** [comment]
![il_570xn 782675793_sni8](https://cloud.githubusercontent.com/assets/69169/11132044/901c58d4-8942-11e5-9622-4548281b4e33.jpg)

**Comment by simurai** [comment]
Waaaaait...

![64922817](https://cloud.githubusercontent.com/assets/378023/11212919/559be2ea-8d7c-11e5-8eca-825c37f4c286.jpg)

- [x] Match other ports #57
- [ ] Unify dark and light
- [ ] `1.0.0` :tada:

**Comment by simurai** [comment]
Ok.. `1.0.0` is released. :tada: 

@schmittyjd Thanks for all your contributions.
