### ISSUE TITLE
Too Much Java Syntax Highlighting

### ISSUE THREAD

**Issue by wuihee** [atom/solarized-dark-syntax#89]
When working with Java, there is too much syntax highlighting. So much so that it makes code sometimes unreadable.

![java_highlighting](https://user-images.githubusercontent.com/22602317/27087780-cad80668-500a-11e7-991e-727340f71bdf.PNG)

This is the original java syntax highlighting found on http://ethanschoonover.com/solarized.
![original_java_highlighting](https://user-images.githubusercontent.com/22602317/27087835-eb17b608-500a-11e7-9646-3236d93e5031.png)

Compared to the solarized theme in Atom.
![java_highlighting2](https://user-images.githubusercontent.com/22602317/27087855-fb6ed2a2-500a-11e7-8594-82c5ec9277b7.PNG)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
